sbatch run_train_nn_with_subsetted_train_sites.sh train_baseline_local_models.yaml channels 3 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_baseline_local_models.yaml channels 4 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_baseline_local_models.yaml channels 12 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_baseline_local_models.yaml channels 15 no

sbatch run_train_nn_with_subsetted_train_sites.sh train_pretrained_xception_model.yaml layers_tuned 1 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_pretrained_xception_model.yaml layers_tuned 2 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_pretrained_xception_model.yaml layers_tuned 3 no

sbatch run_train_nn_with_subsetted_train_sites.sh train_randominit_xception_model_no_latlons.yaml layers_tuned 1 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_randominit_xception_model_no_latlons.yaml layers_tuned 2 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_randominit_xception_model_no_latlons.yaml layers_tuned 3 no

sbatch run_train_nn_with_subsetted_train_sites.sh train_randominit_xception_model_latlons.yaml layers_tuned 1 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_randominit_xception_model_latlons.yaml layers_tuned 2 no
sbatch run_train_nn_with_subsetted_train_sites.sh train_randominit_xception_model_latlons.yaml layers_tuned 3 no

sbatch run_train_nn_with_subsetted_train_sites.sh train_unet_randominit.yaml channels 12 no

sbatch run_train_nn_with_subsetted_train_sites.sh train_unet_ssl4eoweights.yaml freeze_backbone True no
sbatch run_train_nn_with_subsetted_train_sites.sh train_unet_ssl4eoweights.yaml freeze_backbone False no

sbatch run_train_nn_with_subsetted_train_sites.sh train_baseline_local_models.yaml channels 12 subset_train
sbatch run_train_nn_with_subsetted_train_sites.sh train_pretrained_xception_model.yaml layers_tuned 3 subset_train
