# lightning.pytorch==2.0.0
seed_training: 100
splits_to_do:
  - 0
  # - 1
  # - 2 
  # - 3
base_name: 'experiment_results'
exp_name: 'test_unet'
version_id_base: 'unet_resnet18_randominit'
data:
  split_seed: 10
  num_image_channels: 12
  datamodule:
    batch_size: 128
    patch_size: 64
    length: 10000
    num_workers: 12
    eval_pad: 0
task:
  model: 'unet'
  backbone: 'resnet18'
  loss: 'mse'
  in_channels: 12
  lr: 0.001
  weight_decay: 0.01
  nan_val_mask: -9999.
  pad_pixels: 0
    
trainer:
  min_epochs: 1
  max_epochs: 200
  accelerator: 'gpu'
  devices:
    - 0
