# lightning.pytorch==2.0.0
seed_training: 100
splits_to_do:
  - 0
  - 1
  - 2 
  - 3
base_name: 'experiment_results'
exp_name: 'local_only_models'
version_id_base: '128_filters'
data:
  split_seed: 10
  num_image_channels: 4
  datamodule:
    batch_size: 128
    patch_size: 96
    length: 10000
    num_workers: 12
    eval_pad: 5
task:
  model: 'fcn'
  loss: 'mse'
  in_channels: 4
  num_filters: 128
  lr: 0.001
  weight_decay: 0.01
  nan_val_mask: -9999.
  pad_pixels: 5
    
trainer:
  min_epochs: 1
  max_epochs: 100
  accelerator: 'gpu'
  devices:
    - 0
